// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        print("android");
        return android;
      case TargetPlatform.iOS:
        print("iOS");
        return android;
      case TargetPlatform.macOS:
        print("macos");
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLkLlsBPbC79k5d9eiwc0gmj8B0ONQ_m0',
    appId: '1:200260471892:web:c267600a854dc44be231c1',
    messagingSenderId: '200260471892',
    projectId: 'whomii-5bd88',
    authDomain: 'whomii-5bd88.firebaseapp.com',
    storageBucket: 'whomii-5bd88.appspot.com',
    measurementId: 'G-ZMM9T519PV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZf_BEM7QXHBaBEzHJLczDbwf7ORw1AX4',
    appId: '1:200260471892:android:6e0d0c847b8df961e231c1',
    messagingSenderId: '200260471892',
    projectId: 'whomii-5bd88',
    storageBucket: 'whomii-5bd88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIAreTrXpGpaN4D778mZYPqBClgvhl_rk',
    appId: '1:200260471892:ios:9fb34d1c910c6789e231c1',
    messagingSenderId: '200260471892',
    projectId: 'whomii-5bd88',
    storageBucket: 'whomii-5bd88.appspot.com',
    iosClientId:
        '200260471892-obts6c4ds6ms5m9mrl7rth5tdffjq7d0.apps.googleusercontent.com',
    iosBundleId: 'com.disargames.whomii',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIAreTrXpGpaN4D778mZYPqBClgvhl_rk',
    appId: '1:200260471892:ios:07998bb1410f352ce231c1',
    messagingSenderId: '200260471892',
    projectId: 'whomii-5bd88',
    storageBucket: 'whomii-5bd88.appspot.com',
    iosClientId:
        '200260471892-53bslhofo4e1pg76j5vgb3bbfvpjud18.apps.googleusercontent.com',
    iosBundleId: 'com.whomii.whomii.RunnerTests',
  );
}
